eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_HOST_URL:http://localhost}:${EUREKA_PORT:8761}/eureka
  instance:
    hostname: ${EUREKA_HOST:localhost}
